openapi: 3.0.0
info:
  version: 0.0.3-oas3
  title: StockPredictor
  description: Adjusted Closing Price Stock Ticker Predictor
  contact:
    name: Max Roesler
servers:
  - url: 'http://localhost:8080/'
paths:
  /timeframe/<start>/<end>/:
    get:
      tags:
        - TIMEFRAME
      summary: Start & end time of model
      operationId: nasdaq.timeframe
      description: Updates timeframe to use for stock prediction
      parameters:
           - in: path
             name: start
             required: true
             schema:
              type: string
              items:
               type: number
              minItems: 3
              maxItems: 3
           - in: path
             name: end
             required: true
             schema:
              type: string
              items:
               type: number
              minItems: 3
              maxItems: 3
      responses:
        '200':
          description: Successfully updated dates
        '405':
          description: The inputs are invalid
  /nasdaq/<ticker>/<days>/:
    get:
      tags:
        - TICKER
      operationId: nasdaq.nasdaq
      description: Uses ticker to predict stock price in number of days
      parameters:
           - in: path
             name: ticker
             required: true
             schema:
              type: string
           - in: path
             name: days
             required: true
             schema:
              type: string
      responses:
        '200':
          description: Predicted prices
        '405':
          description: The inputs need to be correct
  /dataframe/<start>/<end>/:
    get:
      tags:
        - DATAFRAME
      summary: Update stock tickers for NASDAQ model
      operationId: nasdaq.collectDataframe
      description: Updates stock tickers to use for stock prediction
      parameters:
           - in: path
             name: start
             required: true
             schema:
              type: string
              items:
               type: number
              minItems: 3
              maxItems: 3
           - in: path
             name: end
             required: true
             schema:
              type: string
              items:
               type: number
              minItems: 3
              maxItems: 3
      responses:
        '200':
          description: Successfully updated stock tickers
        '405':
          description: The inputs are invalid

